NNFFT - Nonequispaced in time and frequency FFT
Direct and fast computation of the discrete nonequispaced in time and frequency Fourier transform.
Data Structures
struct nnfft_plan
Structure for a transform plan.
Defines
#define MALLOC_V (1U<< 11)
If this flag is set, (de)allocation of the frequency node vector is done.
Functions
void nnfft_init (nnfft_plan *ths_plan, int d, int N_total, int M_total, int *N)
Creates a transform plan.
void nnfft_init_guru (nnfft_plan *ths_plan, int d, int N_total, int M_total, int *N, int *N1, int m, unsigned nnfft_flags)
Creates a transform plan.
void nndft_trafo (nnfft_plan *ths_plan)
Executes a direct NNDFT, i.e.
void nndft_adjoint (nnfft_plan *ths_plan)
Executes a direct adjoint NNDFT, i.e.
void nnfft_trafo (nnfft_plan *ths_plan)
Executes a NNFFT, i.e.
void nnfft_adjoint (nnfft_plan *ths_plan)
Executes a adjoint NNFFT, i.e.
void nnfft_precompute_lin_psi (nnfft_plan *ths_plan)
Precomputation for a transform plan.
void nnfft_precompute_psi (nnfft_plan *ths_plan)
Precomputation for a transform plan.
void nnfft_precompute_full_psi (nnfft_plan *ths_plan)
Precomputation for a transform plan.
void nnfft_precompute_phi_hut (nnfft_plan *ths_plan)
Precomputation for a transform plan.
void nnfft_finalize (nnfft_plan *ths_plan)
Destroys a plan.
Detailed Description
Direct and fast computation of the discrete nonequispaced in time and frequency Fourier transform.
Define Documentation
#define MALLOC_V (1U<< 11)
If this flag is set, (de)allocation of the frequency node vector is done.
See also: nnfft_init
nnfft_init_guru
nnfft_finalize
Author: Tobias Knopp
Definition at line 958 of file nfft3.h.
Referenced by nnfft_finalize(), nnfft_init(), and reconstruct().
Function Documentation
void nnfft_init (nnfft_plan * ths_plan, int d, int N_total, int M_total, int * N)
Creates a transform plan.
ths_plan The plan for the transform
d The dimension
N_total The number of nodes $v$
M_total The number of nodes $x$
N The bandwidth $N$
Author: Tobias Knopp
Definition at line 573 of file nnfft.c.
References FFT_OUT_OF_PLACE, FFTW_INIT, MALLOC_F, MALLOC_F_HAT, MALLOC_V, MALLOC_X, PRE_PHI_HUT, and PRE_PSI.
void nnfft_init_guru (nnfft_plan * ths_plan, int d, int N_total, int M_total, int * N, int * N1, int m, unsigned nnfft_flags)
Creates a transform plan.
ths_plan The plan for the transform
d The dimension
N_total The number of nodes $v$
M_total The number of nodes $x$
N The bandwidth $N$
N1 The oversampled bandwidth $N$
m The cut-off parameter
nnfft_flags The flags
Author: Tobias Knopp
Definition at line 538 of file nnfft.c.
References FFT_OUT_OF_PLACE, FFTW_INIT, MALLOC_F_HAT, PRE_FULL_PSI, PRE_LIN_PSI, PRE_PHI_HUT, and PRE_PSI.
Referenced by reconstruct().
void nndft_trafo (nnfft_plan * ths_plan)
Executes a direct NNDFT, i.e.
computes for $j=0,...,M_{total}-1$
 f(x_j) = \sum_{k = 0}^{N_{total}-1} \hat{f}(v_k) {\rm e}^{-2 \pi \mbox{\rm\scriptsize i} v_k x_j \odot N} 
ths_plan The plan
Author: Tobias Knopp
Definition at line 64 of file nnfft.c.
void nndft_adjoint (nnfft_plan * ths_plan)
Executes a direct adjoint NNDFT, i.e.
computes for $k=0,...,N_{total}-1$
 \hat{f}(v_k) = \sum_{j = 0}^{M_{total}-1} f(x_j) {\rm e}^{2 \pi \mbox{\rm\scriptsize i} v_k x_j \odot N} 
ths_plan The plan
Author: Tobias Knopp
Definition at line 65 of file nnfft.c.
void nnfft_trafo (nnfft_plan * ths_plan)
Executes a NNFFT, i.e.
computes for $j=0,...,M_{total}-1$
 f(x_j) = \sum_{k = 0}^{N_{total}-1} \hat{f}(v_k) {\rm e}^{-2 \pi \mbox{\rm\scriptsize i} v_k x_j \odot N} 
ths_plan The plan
Author: Tobias Knopp
Definition at line 270 of file nnfft.c.
References nfft_trafo().
void nnfft_adjoint (nnfft_plan * ths_plan)
Executes a adjoint NNFFT, i.e.
computes for $k=0,...,N_{total}-1$
 \hat{f}(v_k) = \sum_{j = 0}^{M_{tota}l-1} f(x_j) {\rm e}^{2 \pi \mbox{\rm\scriptsize i} v_k x_j \odot N} 
ths_plan The plan
Author: Tobias Knopp
Definition at line 294 of file nnfft.c.
References nfft_adjoint().
void nnfft_precompute_lin_psi (nnfft_plan * ths_plan)
Precomputation for a transform plan.
ths_plan The pointer to a nfft plan
Author: Tobias Knopp
precomputes equally spaced values of the window function psi
if PRE_LIN_PSI is set the application program has to call this routine
Definition at line 342 of file nnfft.c.
References nfft_precompute_lin_psi().
Referenced by reconstruct().
void nnfft_precompute_psi (nnfft_plan * ths_plan)
Precomputation for a transform plan.
ths_plan The pointer to a nfft plan
Author: Tobias Knopp
precomputes the values of the window function psi in a tensor product form
if PRE_PSI is set the application program has to call this routine after setting the nodes x
Definition at line 360 of file nnfft.c.
References nfft_precompute_psi().
Referenced by nnfft_precompute_full_psi(), and reconstruct().
void nnfft_precompute_full_psi (nnfft_plan * ths_plan)
Precomputation for a transform plan.
ths_plan The pointer to a nfft plan
Author: Tobias Knopp
precomputes the values of the window function psi and their indices in non tensor product form
if PRE_FULL_PSI is set the application program has to call this routine after setting the nodes x
Definition at line 399 of file nnfft.c.
References nfft_precompute_full_psi(), and nnfft_precompute_psi().
Referenced by reconstruct().
void nnfft_precompute_phi_hut (nnfft_plan * ths_plan)
Precomputation for a transform plan.
ths_plan The pointer to a nfft plan
Author: Tobias Knopp
precomputes the values of the fourier transformed window function, i.e. phi_hut
if PRE_PHI_HUT is set the application program has to call this routine after setting the nodes v
Definition at line 320 of file nnfft.c.
Referenced by reconstruct().
void nnfft_finalize (nnfft_plan * ths_plan)
Destroys a plan.
ths_plan The plan
Author: Tobias Knopp
Definition at line 608 of file nnfft.c.
References MALLOC_F, MALLOC_F_HAT, MALLOC_V, MALLOC_X, nfft_finalize(), PRE_FULL_PSI, PRE_LIN_PSI, PRE_PHI_HUT, and PRE_PSI.
Referenced by reconstruct().