quadratureS2_test
Enumerations
enum boolean { NO = 0,
YES = 1,
NO = 0,
YES = 1
 }
Enumeration for parameter values.
enum testtype { ERROR = 0,
TIMING = 1
 }
Enumeration for test modes.
enum gridtype {
GRID_GAUSS_LEGENDRE = 0,
GRID_CLENSHAW_CURTIS = 1,
GRID_HEALPIX = 2,
GRID_EQUIDISTRIBUTION = 3,
GRID_EQUIDISTRIBUTION_UNIFORM = 4
 }
Enumeration for quadrature grid types.
enum functiontype {
FUNCTION_RANDOM_BANDLIMITED = 0,
FUNCTION_F1 = 1,
FUNCTION_F2 = 2,
FUNCTION_F3 = 3,
FUNCTION_F4 = 4,
FUNCTION_F5 = 5,
FUNCTION_F6 = 6
 }
Enumeration for test functions.
enum modes { USE_GRID = 0,
RANDOM = 1
 }
TODO Add comment here.
Functions
int main (int argc, char **argv)
The main program.
Enumeration Type Documentation
enum boolean
Enumeration for parameter values.
Enumerator:
NO
YES
NO
YES
Definition at line 44 of file quadratureS2.c.
enum testtype
Enumeration for test modes.
Enumerator:
ERROR
TIMING
Definition at line 47 of file quadratureS2.c.
enum gridtype
Enumeration for quadrature grid types.
Enumerator:
GRID_GAUSS_LEGENDRE
GRID_CLENSHAW_CURTIS
GRID_HEALPIX
GRID_EQUIDISTRIBUTION
GRID_EQUIDISTRIBUTION_UNIFORM
Definition at line 50 of file quadratureS2.c.
enum functiontype
Enumeration for test functions.
Enumerator:
FUNCTION_RANDOM_BANDLIMITED
FUNCTION_F1
FUNCTION_F2
FUNCTION_F3
FUNCTION_F4
FUNCTION_F5
FUNCTION_F6
Definition at line 54 of file quadratureS2.c.
enum modes
TODO Add comment here.
Enumerator:
USE_GRID
RANDOM
Definition at line 59 of file quadratureS2.c.
Function Documentation
int main (int argc, char ** argv)
The main program.
Parameters:
argc The number of arguments
argv An array containing the arguments as C-strings
Returns: Exit code
Definition at line 69 of file quadratureS2.c.
References ERROR, nfsft_plan::f, nfsft_plan::f_hat, FFT_OUT_OF_PLACE, FFTW_INIT, FUNCTION_F1, FUNCTION_F2, FUNCTION_F3, FUNCTION_F4, FUNCTION_F5, FUNCTION_F6, FUNCTION_RANDOM_BANDLIMITED, GRID_CLENSHAW_CURTIS, GRID_EQUIDISTRIBUTION, GRID_EQUIDISTRIBUTION_UNIFORM, GRID_GAUSS_LEGENDRE, GRID_HEALPIX, nfsft_plan::N_total, ndsft_adjoint(), ndsft_trafo(), nfft_error_l_2_complex(), nfft_error_l_infty_complex(), nfft_free(), nfft_malloc(), NFFT_MAX, nfft_second(), nfsft_adjoint(), NFSFT_F_HAT_SIZE, nfsft_finalize(), nfsft_forget(), NFSFT_INDEX, nfsft_init_guru(), NFSFT_NO_FAST_ALGORITHM, NFSFT_NORMALIZED, nfsft_precompute(), nfsft_precompute_x(), nfsft_trafo(), NFSFT_USE_DPT, NFSFT_USE_NDFT, NO, PI, PRE_PHI_HUT, PRE_PSI, RANDOM, nfsft_wisdom::threshold, TIMING, and nfsft_plan::x.