MRI - Transforms in magnetic resonance imaging
Data Structures
struct mri_inh_2d1d_plan
The structure for the transform plan.
struct mri_inh_3d_plan
The structure for the transform plan.
Functions
void mri_inh_2d1d_trafo (mri_inh_2d1d_plan *ths)
Executes a mri transformation considering the field inhomogeneity with the 2d1d method, i.e.
void mri_inh_2d1d_adjoint (mri_inh_2d1d_plan *ths)
Executes an adjoint mri transformation considering the field inhomogeneity with the 2d1d method, i.e.
void mri_inh_2d1d_init_guru (mri_inh_2d1d_plan *ths, int *N, int M, int *n, int m, double sigma, unsigned nfft_flags, unsigned fftw_flags)
Creates a transform plan.
void mri_inh_2d1d_finalize (mri_inh_2d1d_plan *ths)
Destroys a plan.
void mri_inh_3d_trafo (mri_inh_3d_plan *ths)
Executes a mri transformation considering the field inhomogeneity with the 3d method, i.e.
void mri_inh_3d_adjoint (mri_inh_3d_plan *ths)
Executes an adjoint mri transformation considering the field inhomogeneity with the 3d method, i.e.
void mri_inh_3d_init_guru (mri_inh_3d_plan *ths, int *N, int M, int *n, int m, double sigma, unsigned nfft_flags, unsigned fftw_flags)
void mri_inh_3d_finalize (mri_inh_3d_plan *ths)
Destroys a plan.
Function Documentation
void mri_inh_2d1d_trafo (mri_inh_2d1d_plan * ths)
Executes a mri transformation considering the field inhomogeneity with the 2d1d method, i.e.
computes for $j=0,...,M_{total}-1$
 f(x_j) = \sum_{k \in I_N^2} \hat{f}(k) {\rm e}^{\mbox{\rm\scriptsize i} t_j \omega(k)} {\rm e}^{-2 \pi \mbox{\rm\scriptsize i} k x_j} 
ths_plan The plan
Author: Tobias Knopp
Definition at line 40 of file mri.c.
References window_funct_plan_::m, window_funct_plan_::n, nfft_trafo(), and PI.
Referenced by construct().
void mri_inh_2d1d_adjoint (mri_inh_2d1d_plan * ths)
Executes an adjoint mri transformation considering the field inhomogeneity with the 2d1d method, i.e.
computes for $k \in I_N^2$
 \hat{f}(k) = \sum_{j=0}^{M_{total}-1} f(x_j) {\rm e}^{\mbox{\rm\scriptsize i} t_j \omega(k)} {\rm e}^{-2 \pi \mbox{\rm\scriptsize i} k x_j} 
ths_plan The plan
Author: Tobias Knopp
Definition at line 82 of file mri.c.
References window_funct_plan_::m, window_funct_plan_::n, nfft_adjoint(), and PI.
void mri_inh_2d1d_init_guru (mri_inh_2d1d_plan * ths, int * N, int M, int * n, int m, double sigma, unsigned nfft_flags, unsigned fftw_flags)
Creates a transform plan.
ths_plan The plan for the transform
N The bandwidth $N$
M_total The number of nodes $x$
n The oversampled bandwidth $N$
m The cut-off parameter
sigma The oversampling factor
nnfft_flags The flags
Author: Tobias Knopp
Definition at line 134 of file mri.c.
References nfft_init_guru().
Referenced by construct().
void mri_inh_2d1d_finalize (mri_inh_2d1d_plan * ths)
Destroys a plan.
ths_plan The plan
Author: Tobias Knopp
Definition at line 149 of file mri.c.
References nfft_finalize().
Referenced by construct().
void mri_inh_3d_trafo (mri_inh_3d_plan * ths)
Executes a mri transformation considering the field inhomogeneity with the 3d method, i.e.
computes for $j=0,...,M_{total}-1$
 f(x_j) = \sum_{k \in I_N^2} \hat{f}(k) {\rm e}^{\mbox{\rm\scriptsize i} t_j \omega(k)} {\rm e}^{-2 \pi \mbox{\rm\scriptsize i} k x_j} 
ths_plan The plan
Author: Tobias Knopp
Definition at line 164 of file mri.c.
References window_funct_plan_::m, window_funct_plan_::n, and nfft_trafo().
Referenced by construct().
void mri_inh_3d_adjoint (mri_inh_3d_plan * ths)
Executes an adjoint mri transformation considering the field inhomogeneity with the 3d method, i.e.
computes for $k \in I_N^2$
 \hat{f}(k) = \sum_{j=0}^{M_{total}-1} f(x_j) {\rm e}^{\mbox{\rm\scriptsize i} t_j \omega(k)} {\rm e}^{-2 \pi \mbox{\rm\scriptsize i} k x_j} 
ths_plan The plan
Author: Tobias Knopp
Definition at line 196 of file mri.c.
References window_funct_plan_::m, window_funct_plan_::n, and nfft_adjoint().
void mri_inh_3d_finalize (mri_inh_3d_plan * ths)
Destroys a plan.
ths_plan The plan
Author: Tobias Knopp
Definition at line 238 of file mri.c.
References nfft_finalize().
Referenced by construct().