Util - Auxilliary functions
Include header for FFTW3 library for its complex type.
Defines
#define TIC(a)
Timing, method works since the inaccurate timer is updated mostly in the measured function.
#define TOC(a)
#define TIC_FFTW(a)
#define TOC_FFTW(a)
#define NFFT_SWAP_complex(x, y)
Swapping of two vectors.
#define NFFT_SWAP_double(x, y)
Swapping of two vectors.
#define PI 3.141592653589793238462643383279502884197169399375105820974944592
Formerly known to be an irrational number.
#define PI2 6.283185307179586476925286766559005768394338798750211641949889185
#define PI4 12.56637061435917295385057353311801153678867759750042328389977837
#define NFFT_MAX(a, b) ((a)>(b)? (a) : (b))
Maximum of its two arguments.
#define NFFT_MIN(a, b) ((a)<(b)? (a) : (b))
Mimimum of its two arguments.
Functions
double nfft_second (void)
Actual used CPU time in seconds; calls getrusage, limited accuracy.
int nfft_total_used_memory (void)
Actual used memory in bytes; calls mallinfo if define HAVE_MALLOC_H.
int nfft_ld (int m)
Integer logarithm of 2.
int nfft_int_2_pow (int a)
Integer power of 2.
int nfft_next_power_of_2 (int N)
Computes $n\ge N$ such that $n=2^j,\, j\in\mathbb{N}_0$.
void nfft_next_power_of_2_exp (int N, int *N2, int *t)
Computes ?
double nfft_sinc (double x)
Computes the sinus cardinalis $\frac{sin\left(x\right)}{x}$.
double nfft_bspline_old (int k, double x, double *A)
To test the new one.
double nfft_bspline (int k, double x, double *scratch)
Computes the B-spline $M_{k,0}\left(x\right)$, scratch is used for de Boor's scheme.
double nfft_i0 (double x)
Modified Bessel function of order zero; adapted from Stephen Moshier's Cephes Math Library Release 2.8.
int nfft_prod_int (int *vec, int d)
Computes integer $\prod_{t=0}^{d-1} v_t$.
int nfct_prod_int (int *vec, int d)
Computes integer $\prod_{t=0}^{d-1} v_t$.
int nfst_prod_minus_a_int (int *vec, int a, int d)
Computes integer $\prod_{t=0}^{d-1} v_t-a$.
int nfft_plain_loop (int *idx, int *N, int d)
Computes $\sum_{t=0}^{d-1} i_t \prod_{t'=t+1}^{d-1} N_{t'}$.
double nfft_prod_real (double *vec, int d)
Computes double $\prod_{t=0}^{d-1} v_t$.
double nfft_dot_complex (fftw_complex *x, int n)
Computes the inner/dot product $x^H x$.
double nfft_dot_double (double *x, int n)
Computes the inner/dot product $x^H x$.
double nfft_dot_w_complex (fftw_complex *x, double *w, int n)
Computes the weighted inner/dot product $x^H (w \odot x)$.
double nfft_dot_w_double (double *x, double *w, int n)
Computes the weighted inner/dot product $x^H (w \odot x)$.
double nfft_dot_w_w2_complex (fftw_complex *x, double *w, double *w2, int n)
Computes the weighted inner/dot product $x^H (w1\odot w2\odot w2 \odot x)$.
double nfft_dot_w2_complex (fftw_complex *x, double *w2, int n)
Computes the weighted inner/dot product $x^H (w2\odot w2 \odot x)$.
void nfft_cp_complex (fftw_complex *x, fftw_complex *y, int n)
Copies $x \leftarrow y$.
void nfft_cp_double (double *x, double *y, int n)
Copies $x \leftarrow y$.
void nfft_cp_a_complex (fftw_complex *x, double a, fftw_complex *y, int n)
Copies $x \leftarrow a y$.
void nfft_cp_w_complex (fftw_complex *x, double *w, fftw_complex *y, int n)
Copies $x \leftarrow w\odot y$.
void nfft_cp_w_double (double *x, double *w, double *y, int n)
Copies $x \leftarrow w\odot y$.
void nfft_upd_axpy_complex (fftw_complex *x, double a, fftw_complex *y, int n)
Updates $x \leftarrow a x + y$.
void nfft_upd_axpy_double (double *x, double a, double *y, int n)
Updates $x \leftarrow a x + y$.
void nfft_upd_xpay_complex (fftw_complex *x, double a, fftw_complex *y, int n)
Updates $x \leftarrow x + a y$.
void nfft_upd_xpay_double (double *x, double a, double *y, int n)
Updates $x \leftarrow x + a y$.
void nfft_upd_axpby_complex (fftw_complex *x, double a, fftw_complex *y, double b, int n)
Updates $x \leftarrow a x + b y$.
void nfft_upd_axpby_double (double *x, double a, double *y, double b, int n)
Updates $x \leftarrow a x + b y$.
void nfft_upd_xpawy_complex (fftw_complex *x, double a, double *w, fftw_complex *y, int n)
Updates $x \leftarrow x + a w\odot y$.
void nfft_upd_xpawy_double (double *x, double a, double *w, double *y, int n)
Updates $x \leftarrow x + a w\odot y$.
void nfft_upd_axpwy_complex (fftw_complex *x, double a, double *w, fftw_complex *y, int n)
Updates $x \leftarrow a x + w\odot y$.
void nfft_upd_axpwy_double (double *x, double a, double *w, double *y, int n)
Updates $x \leftarrow a x + w\odot y$.
void nfft_fftshift_complex (fftw_complex *x, int d, int *N)
Swaps each half over N[d]/2.
double nfft_error_l_infty_complex (fftw_complex *x, fftw_complex *y, int n)
Computes $\frac{\|x-y\|_{\infty}}{\|x\|_{\infty}} $.
double nfft_error_l_infty_double (double *x, double *y, int n)
Computes $\frac{\|x-y\|_{\infty}}{\|x\|_{\infty}} $.
double nfft_error_l_infty_1_complex (fftw_complex *x, fftw_complex *y, int n, fftw_complex *z, int m)
Computes $\frac{\|x-y\|_{\infty}}{\|z\|_1} $.
double nfft_error_l_infty_1_double (double *x, double *y, int n, double *z, int m)
Computes $\frac{\|x-y\|_{\infty}}{\|z\|_1} $.
double nfft_error_l_2_complex (fftw_complex *x, fftw_complex *y, int n)
Computes $\frac{\|x-y\|_2}{\|x\|_2} $.
double nfft_error_l_2_double (double *x, double *y, int n)
Computes $\frac{\|x-y\|_2}{\|x\|_2} $.
void nfft_vpr_int (int *x, int n, char *text)
Prints a vector of integer numbers.
void nfft_vpr_double (double *x, int n, const char *text)
Prints a vector of doubles numbers.
void nfft_vpr_complex (fftw_complex *x, int n, const char *text)
Prints a vector of complex numbers.
void nfft_vrand_unit_complex (fftw_complex *x, int n)
Inits a vector of random complex numbers in $[0,1]\times[0,1]{\rm i}$.
void nfft_vrand_shifted_unit_double (double *x, int n)
Inits a vector of random double numbers in $[-1/2,1/2]$.
void nfft_voronoi_weights_1d (double *w, double *x, int M)
Computes non periodic voronoi weights, assumes ordered nodes $x_j$.
void nfft_voronoi_weights_S2 (double *w, double *xi, int M)
Computes voronoi weights for nodes on the sphere S^2.
double nfft_modified_fejer (int N, int kk)
Computes the damping factor for the modified Fejer kernel, ie $\frac{2}{N}\left(1-\frac{\left|2k+1\right|}{N}\right)$.
double nfft_modified_jackson2 (int N, int kk)
Computes the damping factor for the modified Jackson kernel.
double nfft_modified_jackson4 (int N, int kk)
Computes the damping factor for the modified generalised Jackson kernel.
double nfft_modified_sobolev (double mu, int kk)
Computes the damping factor for the modified Sobolev kernel.
double nfft_modified_multiquadric (double mu, double c, int kk)
Computes the damping factor for the modified multiquadric kernel.
int nfft_smbi (const double x, const double alpha, const int nb, const int ize, double *b)
Calculates the modified bessel function $I_{n+\alpha}(x)$, possibly scaled by $\mathrm{e}^{-x}$, for real non-negative $x,alpha$ with $0 \le \alpha < 1$, and $n=0,1,\ldots,nb-1$.
double nfft_lambda (const double z, const double eps)
Computes the function $\Lambda(z,\epsilon) = \frac{\Gamma(z+\epsilon)}{\Gamma(z+1)}$, with $ z + \epsilon > 0$.
Detailed Description
Include header for FFTW3 library for its complex type.
This module implements frequently used utility functions. In particular, this includes simple measurement of resources, evaluation of window functions, vector routines for basic linear algebra tasks, and computation of weights for the inverse transforms.
Define Documentation
#define TIC(a)
Timing, method works since the inaccurate timer is updated mostly in the measured function.
For small times not every call of the measured function will also produce a 'unit' time step. Measuring the fftw might cause a wrong output vector due to the repeated ffts.
Definition at line 72 of file util.h.
Referenced by nfct_adjoint(), nfct_trafo(), nfft_adjoint(), nfft_adjoint_1d(), nfft_adjoint_2d(), nfft_adjoint_3d(), nfft_trafo(), nfft_trafo_1d(), nfft_trafo_2d(), nfft_trafo_3d(), nfst_adjoint(), and nfst_trafo().
#define NFFT_SWAP_complex(x, y)
Value:
{fftw_complex* NFFT_SWAP_temp__; \
  NFFT_SWAP_temp__=(x); (x)=(y); (y)=NFFT_SWAP_temp__;}
Swapping of two vectors.
Definition at line 87 of file util.h.
Referenced by accuracy_pre_lin_psi(), fgt_test_andersson(), fgt_test_error(), fgt_test_error_p(), fgt_test_simple(), glacier_cv(), main(), solver_before_loop_complex(), solver_loop_one_step_cgnr_complex(), solver_loop_one_step_landweber_complex(), solver_loop_one_step_steepest_descent_complex(), taylor_time_accuracy(), and time_accuracy().
#define NFFT_SWAP_double(x, y)
Value:
{double* NFFT_SWAP_temp__; NFFT_SWAP_temp__=(x); \
  (x)=(y); (y)=NFFT_SWAP_temp__;}
Swapping of two vectors.
Definition at line 92 of file util.h.
Referenced by solver_before_loop_double(), solver_loop_one_step_cgnr_double(), solver_loop_one_step_landweber_double(), and solver_loop_one_step_steepest_descent_double().
Function Documentation
double nfft_second (void)
Actual used CPU time in seconds; calls getrusage, limited accuracy.
Actual used CPU time in seconds; calls getrusage, limited accuracy.
functions for vectors, window functions, ... (c) if not stated otherwise: Daniel Potts, Stefan Kunis Actual used CPU time in seconds. Calls getrusage, limited accuracy
Definition at line 43 of file util.c.
Referenced by comparison_fft(), fgt_test_measure_time(), fields_fastsum_precompute(), inverse_linogram_fft(), inverse_mpolar_fft(), linogram_dft(), linogram_fft(), main(), mpolar_dft(), mpolar_fft(), ndft_time(), reconstruct(), taylor_time_accuracy(), and time_accuracy().
double nfft_i0 (double x)
Modified Bessel function of order zero; adapted from Stephen Moshier's Cephes Math Library Release 2.8.
Modified Bessel function of order zero; adapted from Stephen Moshier's Cephes Math Library Release 2.8.
Cephes Math Library Release 2.8: June, 2000 Copyright 1984, 1987, 2000 by Stephen L. Moshier
Definition at line 879 of file util.c.
void nfft_voronoi_weights_S2 (double * w, double * xi, int M)
Computes voronoi weights for nodes on the sphere S^2.
Definition at line 1447 of file util.c.
Referenced by main().
int nfft_smbi (const R x, const R alpha, const int nb, const int ize, R * b)
Calculates the modified bessel function $I_{n+\alpha}(x)$, possibly scaled by $\mathrm{e}^{-x}$, for real non-negative $x,alpha$ with $0 \le \alpha < 1$, and $n=0,1,\ldots,nb-1$.
[in] x non-negative real number in $I_{n+\alpha}(x)$
[in] alpha non-negative real number with $0 \le \alpha < 1$ in $I_{n+\alpha}(x)$
[in] nb number of functions to be calculated
[in] ize switch between no scaling (ize = 1) and exponential scaling (ize = 2)
[out] b real output vector to contain $I_{n+\alpha}(x)$, $n=0,1,\ldots,nb-1$
Returns: error indicator. Only if this value is identical to nb, then all values in b have been calculated to full accuracy. If not, errors are indicated using the following scheme:
ncalc < 0: At least one of the arguments was out of range (e.g. nb <= 0, ize neither equals 1 nor 2, $|x| \ge exparg$). In this case, the output vector b is not calculated and ncalc is set to $\min(nb,0)-1$.
0 < ncalc < nb: Not all requested functions could be calculated to full accuracy. This can occur when nb is much larger than |x|. in this case, the values $I_{n+\alpha}(x)$ are calculated to full accuracy for $n=0,1,\ldots,ncalc$. The rest of the values up to $n=0,1,\ldots,nb-1$ is calculated to a lower accuracy.
This program is based on a program written by David J. Sookne [2] that computes values of the Bessel functions $J_{\nu}(x)$ or $I_{\nu}(x)$ for real argument $x$ and integer order $\nu$. modifications include the restriction of the computation to the Bessel function $I_{\nu}(x)$ for non-negative real argument, the extension of the computation to arbitrary non-negative orders $\nu$, and the elimination of most underflow.
References: [1] F. W. J. Olver and D. J. Sookne, A note on backward recurrence algorithms`, Math. Comput. (26), 1972, pp 125 -- 132. [2] D. J. Sookne, `Bessel functions of real argument and int order`, NBS Jour. of Res. B. (77B), 1973, pp. 125 -- 132.
Modified by W. J. Cody, Applied Mathematics Division, Argonne National Laboratory, Argonne, IL, 60439, USA
Modified by Jens Keiner, Institute of Mathematics, University of Lübeck, 23560 Lübeck, Germany
Definition at line 1816 of file util.c.
Referenced by main().
double nfft_lambda (const double z, const double eps)
Computes the function $\Lambda(z,\epsilon) = \frac{\Gamma(z+\epsilon)}{\Gamma(z+1)}$, with $ z + \epsilon > 0$.
This method uses the Lanczos approximation to compute the result; see Glendon Ralph Pugh. An Analysis of The Lanczos Gamma Approximation. PhD Thesis, The University of British Columbia, 2004.
Definition at line 2155 of file util.c.