NFFT - Nonequispaced fast Fourier transform
Direct and fast computation of the nonequispaced discrete Fourier transform.
Data Structures
struct nfft_plan
Structure for a NFFT plan.
Defines
#define PRE_PHI_HUT (1U<< 0)
If this flag is set, the deconvolution step (the multiplication with the diagonal matrix $\mathbf{D}$) uses precomputed values of the Fourier transformed window function.
#define FG_PSI (1U<< 1)
If this flag is set, the convolution step (the multiplication with the sparse matrix $\mathbf{B}$) uses particular properties of the Gaussian window function to trade multiplications for direct calls to exponential function.
#define PRE_LIN_PSI (1U<< 2)
If this flag is set, the convolution step (the multiplication with the sparse matrix $\mathbf{B}$) uses linear interpolation from a lookup table of equispaced samples of the window function instead of exact values of the window function.
#define PRE_FG_PSI (1U<< 3)
If this flag is set, the convolution step (the multiplication with the sparse matrix $\mathbf{B}$) uses particular properties of the Gaussian window function to trade multiplications for direct calls to exponential function (the remaining $2dM$ direct calls are precomputed).
#define PRE_PSI (1U<< 4)
If this flag is set, the convolution step (the multiplication with the sparse matrix $\mathbf{B}$) uses $(2m+2)dM$ precomputed values of the window function.
#define PRE_FULL_PSI (1U<< 5)
If this flag is set, the convolution step (the multiplication with the sparse matrix $\mathbf{B}$) uses $(2m+2)^dM$ precomputed values of the window function, in addition indices of source and target vectors are stored.
#define MALLOC_X (1U<< 6)
If this flag is set, (de)allocation of the node vector is done.
#define MALLOC_F_HAT (1U<< 7)
If this flag is set, (de)allocation of the vector of Fourier coefficients is done.
#define MALLOC_F (1U<< 8)
If this flag is set, (de)allocation of the vector of samples is done.
#define FFT_OUT_OF_PLACE (1U<< 9)
If this flag is set, FFTW uses disjoint input/output vectors.
#define FFTW_INIT (1U<< 10)
If this flag is set, fftw_init/fftw_finalize is called.
#define PRE_ONE_PSI (PRE_LIN_PSI| PRE_FG_PSI| PRE_PSI| PRE_FULL_PSI)
Summarises if precomputation is used within the convolution step (the multiplication with the sparse matrix $\mathbf{B}$).
Functions
void ndft_trafo (nfft_plan *ths)
Computes a NDFT, see the definition.
void ndft_adjoint (nfft_plan *ths)
Computes an adjoint NDFT, see the definition.
void nfft_trafo (nfft_plan *ths)
Computes a NFFT, see the definition.
void nfft_trafo_1d (nfft_plan *ths)
void nfft_trafo_2d (nfft_plan *ths)
void nfft_trafo_3d (nfft_plan *ths)
void nfft_adjoint (nfft_plan *ths)
Computes an adjoint NFFT, see the definition.
void nfft_adjoint_1d (nfft_plan *ths)
void nfft_adjoint_2d (nfft_plan *ths)
void nfft_adjoint_3d (nfft_plan *ths)
void nfft_init_1d (nfft_plan *ths, int N1, int M)
Initialisation of a transform plan, wrapper d=1.
void nfft_init_2d (nfft_plan *ths, int N1, int N2, int M)
Initialisation of a transform plan, wrapper d=2.
void nfft_init_3d (nfft_plan *ths, int N1, int N2, int N3, int M)
Initialisation of a transform plan, wrapper d=3.
void nfft_init (nfft_plan *ths, int d, int *N, int M)
Initialisation of a transform plan, simple.
void nfft_init_advanced (nfft_plan *ths, int d, int *N, int M, unsigned nfft_flags_on, unsigned nfft_flags_off)
Initialisation of a transform plan, advanced.
void nfft_init_guru (nfft_plan *ths, int d, int *N, int M, int *n, int m, unsigned nfft_flags, unsigned fftw_flags)
Initialisation of a transform plan, guru.
void nfft_precompute_one_psi (nfft_plan *ths)
Precomputation for a transform plan.
void nfft_precompute_full_psi (nfft_plan *ths)
Superceded by nfft_precompute_one_psi.
void nfft_precompute_psi (nfft_plan *ths)
Superceded by nfft_precompute_one_psi.
void nfft_precompute_lin_psi (nfft_plan *ths)
Superceded by nfft_precompute_one_psi.
void nfft_check (nfft_plan *ths)
Checks a transform plan for frequently used bad parameter.
void nfft_finalize (nfft_plan *ths)
Destroys a transform plan.
Detailed Description
Direct and fast computation of the nonequispaced discrete Fourier transform.
This module implements the nonequispaced fast Fourier transforms. In the following, we abbreviate the term `nonequispaced fast Fourier transform` by NFFT.
We introduce our notation and nomenclature for discrete Fourier transforms. Let the torus
 \mathbb{T}^d := \left\{ \mathbf{x}=\left(x_t\right)_{t=0,\hdots,d-1}\in\mathbb{R}^{d}: \; - \frac{1}{2} \le x_t < \frac{1}{2},\; t=0,\hdots,d-1 \right\} 
 of dimension $d$ be given. It will serve as domain from which the nonequispaced nodes $\mathbf{x}$ are taken. The sampling set is given by ${\cal X}:=\{\mathbf{x}_j \in {\mathbb T}^d: \,j=0,\hdots,M-1\}$. Possible frequencies $\mathbf{k}$ are collected in the multi index set
 I_{\mathbf{N}} := \left\{ \mathbf{k}=\left(k_t\right)_{t=0,\hdots,d-1}\in \mathbb{Z}^d: - \frac{N_t}{2} \le k_t < \frac{N_t}{2} ,\;t=0,\hdots,d-1 \right\}. 
Our concern is the computation of the nonequispaced discrete Fourier transform (NDFT)
 f_j = \sum_{\mathbf{k}\in I_{\mathbf{N}}} \hat{f}_{\mathbf{k}} {\rm e}^{-2\pi{\rm i} \mathbf{k}\mathbf{x}_j}, \qquad j=0,\hdots,M-1. 
 The corresponding adjoint NDFT is the computation of
 \hat f_{\mathbf{k}}=\sum_{j=0}^{M-1} f_j {\rm e}^{+2\pi{\rm i} \mathbf{k}\mathbf{x}_j}, \qquad \mathbf{k}\in I_{\mathbf{N}}. 
 Direct implementations are given by ndft_trafo and ndft_adjoint taking ${\cal O}(|I_{\mathbf{N}}|M)$ floating point operations. Approximative realisations take only ${\cal O}(|I_{\mathbf{N}}|\log|I_{\mathbf{N}}|+M)$ floating point operations. These are provided by nfft_trafo and nfft_adjoint, respectively.
Define Documentation
#define PRE_PHI_HUT (1U<< 0)
If this flag is set, the deconvolution step (the multiplication with the diagonal matrix $\mathbf{D}$) uses precomputed values of the Fourier transformed window function.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
Author: Stefan Kunis
Definition at line 210 of file nfft3.h.
Referenced by accuracy_pre_lin_psi(), construct(), fastsum_init_guru(), fgt_init_guru(), glacier(), glacier_cv(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_dft(), linogram_fft(), main(), mpolar_dft(), mpolar_fft(), nfct_finalize(), nfft_adjoint_1d(), nfft_adjoint_2d(), nfft_adjoint_3d(), nfft_finalize(), nfft_init(), nfft_trafo_1d(), nfft_trafo_2d(), nfft_trafo_3d(), nfsft_init_advanced(), nfsoft_init_advanced(), nfst_finalize(), nnfft_finalize(), nnfft_init(), nnfft_init_guru(), polar_dft(), polar_fft(), Radon_trafo(), reconstruct(), taylor_time_accuracy(), and time_accuracy().
#define FG_PSI (1U<< 1)
If this flag is set, the convolution step (the multiplication with the sparse matrix $\mathbf{B}$) uses particular properties of the Gaussian window function to trade multiplications for direct calls to exponential function.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
Author: Stefan Kunis
Definition at line 223 of file nfft3.h.
Referenced by nfsoft_precompute(), and time_accuracy().
#define PRE_LIN_PSI (1U<< 2)
If this flag is set, the convolution step (the multiplication with the sparse matrix $\mathbf{B}$) uses linear interpolation from a lookup table of equispaced samples of the window function instead of exact values of the window function.
At the moment a table of size $(K+1)d$ is used, where $K=2^{10}(m+1)$. An estimate for the size of the lookup table with respect to the target accuracy should be implemented.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
Author: Stefan Kunis
Definition at line 240 of file nfft3.h.
Referenced by accuracy_pre_lin_psi(), fastsum_precompute(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_fft(), mpolar_fft(), nfft_finalize(), nfft_precompute_one_psi(), nfsoft_init_guru(), nnfft_finalize(), nnfft_init_guru(), polar_fft(), Radon_trafo(), reconstruct(), and time_accuracy().
#define PRE_FG_PSI (1U<< 3)
If this flag is set, the convolution step (the multiplication with the sparse matrix $\mathbf{B}$) uses particular properties of the Gaussian window function to trade multiplications for direct calls to exponential function (the remaining $2dM$ direct calls are precomputed).
See also: nfft_init
nfft_init_advanced
nfft_init_guru
Author: Stefan Kunis
Definition at line 253 of file nfft3.h.
Referenced by nfft_finalize(), nfft_precompute_one_psi(), taylor_time_accuracy(), and time_accuracy().
#define PRE_PSI (1U<< 4)
If this flag is set, the convolution step (the multiplication with the sparse matrix $\mathbf{B}$) uses $(2m+2)dM$ precomputed values of the window function.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
Author: Stefan Kunis
Definition at line 265 of file nfft3.h.
Referenced by construct(), fastsum_init_guru(), fastsum_precompute(), fgt_init_guru(), fgt_init_node_dependent(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_dft(), linogram_fft(), main(), mpolar_dft(), mpolar_fft(), nfct_finalize(), nfft_finalize(), nfft_init(), nfft_precompute_one_psi(), nfsft_init_advanced(), nfsoft_init_advanced(), nfsoft_precompute(), nfst_finalize(), nfst_full_psi(), nnfft_finalize(), nnfft_init(), nnfft_init_guru(), polar_dft(), polar_fft(), Radon_trafo(), reconstruct(), and time_accuracy().
#define PRE_FULL_PSI (1U<< 5)
If this flag is set, the convolution step (the multiplication with the sparse matrix $\mathbf{B}$) uses $(2m+2)^dM$ precomputed values of the window function, in addition indices of source and target vectors are stored.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
Author: Stefan Kunis
Definition at line 278 of file nfft3.h.
Referenced by fastsum_precompute(), glacier(), glacier_cv(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_fft(), mpolar_fft(), nfct_adjoint(), nfct_trafo(), nfft_finalize(), nfft_precompute_one_psi(), nfst_finalize(), nfst_precompute_psi(), nnfft_finalize(), nnfft_init_guru(), polar_fft(), Radon_trafo(), reconstruct(), and time_accuracy().
#define MALLOC_X (1U<< 6)
If this flag is set, (de)allocation of the node vector is done.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
nfft_finalize
Author: Stefan Kunis
Definition at line 289 of file nfft3.h.
Referenced by accuracy_pre_lin_psi(), construct(), fastsum_init_guru(), fgt_init_guru(), glacier(), glacier_cv(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_dft(), linogram_fft(), mpolar_dft(), mpolar_fft(), nfct_finalize(), nfft_finalize(), nfft_init(), nfsoft_init_advanced(), nfst_finalize(), nnfft_finalize(), nnfft_init(), polar_dft(), polar_fft(), Radon_trafo(), reconstruct(), taylor_init(), and time_accuracy().
#define MALLOC_F_HAT (1U<< 7)
If this flag is set, (de)allocation of the vector of Fourier coefficients is done.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
nfft_finalize
Author: Stefan Kunis
Definition at line 301 of file nfft3.h.
Referenced by accuracy_pre_lin_psi(), construct(), fastsum_init_guru(), fgt_init_guru(), glacier(), glacier_cv(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_dft(), linogram_fft(), mpolar_dft(), mpolar_fft(), nfct_finalize(), nfft_finalize(), nfft_init(), nfsoft_init_advanced(), nfst_finalize(), nnfft_finalize(), nnfft_init(), nnfft_init_guru(), polar_dft(), polar_fft(), Radon_trafo(), reconstruct(), taylor_init(), and time_accuracy().
#define MALLOC_F (1U<< 8)
If this flag is set, (de)allocation of the vector of samples is done.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
nfft_finalize
Author: Stefan Kunis
Definition at line 312 of file nfft3.h.
Referenced by accuracy_pre_lin_psi(), construct(), fastsum_init_guru(), glacier(), glacier_cv(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_dft(), linogram_fft(), mpolar_dft(), mpolar_fft(), nfct_finalize(), nfft_finalize(), nfft_init(), nfsoft_init_advanced(), nfst_finalize(), nnfft_finalize(), nnfft_init(), polar_dft(), polar_fft(), Radon_trafo(), reconstruct(), taylor_init(), and time_accuracy().
#define FFT_OUT_OF_PLACE (1U<< 9)
If this flag is set, FFTW uses disjoint input/output vectors.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
nfft_finalize
Author: Stefan Kunis
Definition at line 323 of file nfft3.h.
Referenced by accuracy_pre_lin_psi(), construct(), fastsum_init_guru(), glacier(), glacier_cv(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_dft(), linogram_fft(), main(), mpolar_dft(), mpolar_fft(), nfct_finalize(), nfft_finalize(), nfft_init(), nfsft_init_advanced(), nfsoft_init_advanced(), nfst_finalize(), nnfft_init(), nnfft_init_guru(), polar_dft(), polar_fft(), Radon_trafo(), reconstruct(), taylor_init(), taylor_time_accuracy(), and time_accuracy().
#define FFTW_INIT (1U<< 10)
If this flag is set, fftw_init/fftw_finalize is called.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
nfft_finalize
Author: Stefan Kunis
Definition at line 334 of file nfft3.h.
Referenced by accuracy_pre_lin_psi(), construct(), fastsum_init_guru(), fgt_init_guru(), glacier(), glacier_cv(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_dft(), linogram_fft(), main(), mpolar_dft(), mpolar_fft(), nfct_finalize(), nfft_finalize(), nfft_init(), nfsft_init_advanced(), nfsoft_init_advanced(), nfst_finalize(), nnfft_init(), nnfft_init_guru(), polar_dft(), polar_fft(), Radon_trafo(), reconstruct(), taylor_init(), taylor_time_accuracy(), and time_accuracy().
#define PRE_ONE_PSI (PRE_LIN_PSI| PRE_FG_PSI| PRE_PSI| PRE_FULL_PSI)
Summarises if precomputation is used within the convolution step (the multiplication with the sparse matrix $\mathbf{B}$).
If testing against this flag is positive, nfft_precompute_one_psi has to be called.
See also: nfft_init
nfft_init_advanced
nfft_init_guru
nfft_precompute_one_psi
nfft_finalize
Author: Stefan Kunis
Definition at line 349 of file nfft3.h.
Referenced by glacier(), glacier_cv(), nfsft_precompute_x(), and taylor_time_accuracy().
Function Documentation
void ndft_trafo (nfft_plan * ths)
Computes a NDFT, see the definition.
ths The pointer to a nfft plan
Author: Stefan Kunis, Daniel Potts
Definition at line 148 of file nfft.c.
Referenced by accuracy_pre_lin_psi(), fgt_trafo(), linogram_dft(), mpolar_dft(), ndft_time(), nfsft_trafo(), nfsoft_trafo(), polar_dft(), taylor_time_accuracy(), and time_accuracy().
void ndft_adjoint (nfft_plan * ths)
Computes an adjoint NDFT, see the definition.
ths The pointer to a nfft plan
Author: Stefan Kunis, Daniel Potts
Definition at line 149 of file nfft.c.
Referenced by fgt_trafo(), nfsft_adjoint(), and nfsoft_adjoint().
void nfft_trafo (nfft_plan * ths)
Computes a NFFT, see the definition.
ths The pointer to a nfft plan
Author: Stefan Kunis, Daniel Potts
Definition at line 2771 of file nfft.c.
Referenced by accuracy_pre_lin_psi(), construct(), fastsum_trafo(), fgt_trafo(), fields_fastsum_trafo(), glacier_cv(), linogram_fft(), mpolar_fft(), mri_inh_2d1d_trafo(), mri_inh_3d_trafo(), ndft_time(), nfsoft_trafo(), nnfft_trafo(), polar_fft(), Radon_trafo(), taylor_time_accuracy(), and time_accuracy().
void nfft_adjoint (nfft_plan * ths)
Computes an adjoint NFFT, see the definition.
ths The pointer to a nfft plan
Author: Stefan Kunis, Daniel Potts
Definition at line 2807 of file nfft.c.
Referenced by fastsum_trafo(), fgt_trafo(), fields_fastsum_trafo(), mri_inh_2d1d_adjoint(), mri_inh_3d_adjoint(), nfsoft_adjoint(), nnfft_adjoint(), and reconstruct().
void nfft_init_1d (nfft_plan * ths, int N1, int M)
Initialisation of a transform plan, wrapper d=1.
ths The pointer to a nfft plan
N1 bandwidth
M The number of nodes
Author: Stefan Kunis, Daniel Potts
Definition at line 3089 of file nfft.c.
Referenced by ndft_time().
void nfft_init_2d (nfft_plan * ths, int N1, int N2, int M)
Initialisation of a transform plan, wrapper d=2.
ths The pointer to a nfft plan
N1 bandwidth
N2 bandwidth
M The number of nodes
Author: Stefan Kunis, Daniel Potts
Definition at line 3097 of file nfft.c.
Referenced by construct().
void nfft_init_3d (nfft_plan * ths, int N1, int N2, int N3, int M)
Initialisation of a transform plan, wrapper d=3.
ths The pointer to a nfft plan
N1 bandwidth
N2 bandwidth
N3 bandwidth
M The number of nodes
Author: Stefan Kunis, Daniel Potts
Definition at line 3106 of file nfft.c.
void nfft_init (nfft_plan * ths, int d, int * N, int M)
Initialisation of a transform plan, simple.
ths The pointer to a nfft plan
d The dimension
N The multi bandwidth
M The number of nodes
Author: Stefan Kunis, Daniel Potts
Definition at line 3044 of file nfft.c.
Referenced by nfft_init_1d(), nfft_init_2d(), and nfft_init_3d().
void nfft_init_advanced (nfft_plan * ths, int d, int * N, int M, unsigned nfft_flags_on, unsigned nfft_flags_off)
Initialisation of a transform plan, advanced.
NOT YET IMPLEMENTED!!
ths The pointer to a nfft plan
d The dimension
N The multi bandwidth
M The number of nodes
nfft_flags_on NFFT flags to switch on
nfft_flags_off NFFT flags to switch off
Author: Stefan Kunis, Daniel Potts
void nfft_init_guru (nfft_plan * ths, int d, int * N, int M, int * n, int m, unsigned nfft_flags, unsigned fftw_flags)
Initialisation of a transform plan, guru.
ths The pointer to a nfft plan
d The dimension
N The multi bandwidth
M The number of nodes
n The oversampled multi bandwidth
m The spatial cut-off
nfft_flags NFFT flags to use
fftw_flags_off FFTW flags to use
Author: Stefan Kunis, Daniel Potts
Definition at line 3069 of file nfft.c.
Referenced by accuracy_pre_lin_psi(), construct(), fastsum_init_guru(), fgt_init_guru(), glacier(), glacier_cv(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_dft(), linogram_fft(), mpolar_dft(), mpolar_fft(), mri_inh_2d1d_init_guru(), mri_inh_3d_init_guru(), nfsft_init_guru(), nfsoft_init_guru(), polar_dft(), polar_fft(), Radon_trafo(), reconstruct(), taylor_init(), taylor_time_accuracy(), and time_accuracy().
void nfft_precompute_one_psi (nfft_plan * ths)
Precomputation for a transform plan.
ths The pointer to a nfft plan
Author: Stefan Kunis
wrapper for precompute*_psi
if PRE_*_PSI is set the application program has to call this routine (after) setting the nodes x
Definition at line 2963 of file nfft.c.
Referenced by accuracy_pre_lin_psi(), glacier(), glacier_cv(), nfsft_precompute_x(), nfsoft_precompute(), taylor_time_accuracy(), and time_accuracy().
void nfft_precompute_full_psi (nfft_plan * ths)
Superceded by nfft_precompute_one_psi.
Author: Stefan Kunis
Definition at line 2922 of file nfft.c.
Referenced by fastsum_precompute(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_fft(), mpolar_fft(), nfft_precompute_one_psi(), nnfft_precompute_full_psi(), polar_fft(), Radon_trafo(), and reconstruct().
void nfft_precompute_psi (nfft_plan * ths)
Superceded by nfft_precompute_one_psi.
Author: Stefan Kunis
Definition at line 2902 of file nfft.c.
Referenced by construct(), fastsum_precompute(), fgt_init_node_dependent(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_fft(), mpolar_fft(), nfft_precompute_one_psi(), nnfft_precompute_psi(), polar_fft(), Radon_trafo(), and reconstruct().
void nfft_precompute_lin_psi (nfft_plan * ths)
Superceded by nfft_precompute_one_psi.
Author: Stefan Kunis
Definition at line 2866 of file nfft.c.
Referenced by fastsum_precompute(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_fft(), mpolar_fft(), nfft_precompute_one_psi(), nfsoft_init_guru(), nnfft_precompute_lin_psi(), polar_fft(), Radon_trafo(), and reconstruct().
void nfft_check (nfft_plan * ths)
Checks a transform plan for frequently used bad parameter.
ths The pointer to a nfft plan
Author: Stefan Kunis, Daniel Potts
Definition at line 3116 of file nfft.c.
void nfft_finalize (nfft_plan * ths)
Destroys a transform plan.
ths The pointer to a nfft plan
Author: Stefan Kunis, Daniel Potts
Definition at line 3139 of file nfft.c.
Referenced by accuracy_pre_lin_psi(), construct(), fastsum_finalize(), fgt_finalize(), glacier(), glacier_cv(), inverse_linogram_fft(), inverse_mpolar_fft(), inverse_polar_fft(), Inverse_Radon_trafo(), linogram_dft(), linogram_fft(), mpolar_dft(), mpolar_fft(), mri_inh_2d1d_finalize(), mri_inh_3d_finalize(), ndft_time(), nfsft_finalize(), nfsoft_finalize(), nnfft_finalize(), polar_dft(), polar_fft(), Radon_trafo(), reconstruct(), taylor_finalize(), taylor_time_accuracy(), and time_accuracy().