iterS2_matlab
Enumerations
enum boolean { NO = 0,
YES = 1,
NO = 0,
YES = 1
 }
Enumeration for parameter values.
Functions
int main (int argc, char **argv)
The main program.
Enumeration Type Documentation
enum boolean
Enumeration for parameter values.
Enumerator:
NO
YES
NO
YES
Definition at line 43 of file iterS2.c.
Function Documentation
int main (int argc, char ** argv)
The main program.
Parameters:
argc The number of arguments
argv An array containing the arguments as C-strings
Returns: Exit code
Author: Jens Keiner
Definition at line 55 of file iterS2.c.
References alpha_al_row(), beta_al_row(), CGNE, CGNR, solver_plan_complex::dot_r_iter, nfsft_plan::f, nfsft_plan::f_hat, solver_plan_complex::f_hat_iter, FFT_OUT_OF_PLACE, FFTW_INIT, fpt_finalize(), fpt_init(), fpt_precompute(), fpt_transposed(), gamma_al_row(), nfsft_plan::M_total, nfsft_plan::N_total, nfft_bspline(), nfft_free(), nfft_malloc(), nfft_next_power_of_2_exp(), NFFT_SWAP_complex, nfft_voronoi_weights_S2(), nfsft_finalize(), nfsft_forget(), NFSFT_INDEX, nfsft_init_guru(), NFSFT_MALLOC_F, NFSFT_MALLOC_F_HAT, NFSFT_MALLOC_X, NFSFT_NO_FAST_ALGORITHM, NFSFT_NORMALIZED, nfsft_precompute(), nfsft_precompute_x(), nfsft_trafo(), NFSFT_USE_DPT, NFSFT_USE_NDFT, NFSFT_ZERO_F_HAT, NO, PI, PRE_PHI_HUT, PRE_PSI, PRECOMPUTE_DAMP, PRECOMPUTE_WEIGHT, solver_before_loop_complex(), solver_finalize_complex(), solver_init_advanced_complex(), solver_loop_one_step_complex(), solver_plan_complex::w, solver_plan_complex::w_hat, nfsft_plan::x, and solver_plan_complex::y.